service: web-components-serverless-boiler
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 28
  environment:
    STAGE: ${opt:stage, self:provider.stage}

functions:
  appDirName:
    handler: dist/src/appDirName/lambdaServer.lambdaServer
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
